version: 2.1
orbs:
  ansible: orbss/ansible-playbook@0.0.5

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    steps:
      - checkout
      # -- Build and test here before building image and pushing.
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false 
      # -- Building Docker Image and Pushing to Dockerhub using Packer.
      - ansible/install
      - ansible/playbook:
          playbook: ./.ansible/build.yml

    
