version: 2

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    steps:
      - checkout
      # -- Build and test here before building image and pushing.
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false 
      # -- Building Docker Image and Pushing to Dockerhub.
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t shadak/personal-frontend .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push shadak/personal-frontend:latest
        
      
