- name: Build, Tag and Push Docker Image from Local folder.
  hosts: 127.0.0.1 
  connection: local
  
  tasks:
    - name: Build Docker Image.
      docker_image:
        build:
          args:
            ENV: prod
          path: ../
          pull: yes
        name: shadak/personal-frontend
        source: build
        state: present
        tag: latest
    
    - name: Generate git commit hash.
      command: git log -n 1 --format="%h"
      register: commit_hash

    - name: tag and push image with commit hash.
      docker_image:
        name: shadak/personal-frontend:latest
        push: yes
        source: local

    - name: Push image with latest tag.
      docker_image:
        name: shadak/personal-frontend
        tag: latest
        push: yes
        source: local
