---
- name: Build, Tag and Push Docker Image from Local folder.
  hosts: localhost 
  connection: local
  tasks:
    - name: Login to Docker
      docker_login:
        username: "{{ lookup('env','DOCKER_USERNAME') }}"
        password: "{{ lookup('env','DOCKER_PASSWORD') }}"
      
    - name: Build Docker Image
      docker_image:
        build:
          args:
          path: ../../../../ 
          pull: yes
        name: shadak/personal-frontend
        source: build
        state: present
        tag: latest
  
    - name: Push image with latest tag
      docker_image:
        name: shadak/personal-frontend
        tag: latest
        push: yes
        source: local
